kind: Deployment
apiVersion: apps/v1
metadata:
  name: pet-treats
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-treats
  template:
    metadata:
      labels:
        app: pet-treats
    spec:
      containers:
        - name: pet-treats
          image: localhost:5000/pet-treats
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: pet-treats
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: pet-treats
